#!/usr/bin/env groovy

pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }

        stage("Create EKS Infrastructure") {
            steps {
                script {
                    dir ('jenkins-pipeline/aws') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                        sh 'export echo CLUSTER_NAME=$(terraform output -raw cluster_name)'
                    }
                }
            }
        }

        stage("Remove NGINX") {
            steps {
                script {
                    dir ('jenkins-pipeline/aws') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name $(terraform output -raw cluster_name)'
                        sh 'kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/do/deploy.yaml'
                    }
                }
            }
        }

        stage("Install NGINX & Prometheus") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l'
                        sh 'terraform init -upgrade'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage("Install Certificate Manager with Helm") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l'
                        sh 'helm repo add jetstack https://charts.jetstack.io'
                        sh 'helm repo update'
                        sh 'kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml'
                        // sh 'helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0'
                        sh 'kubectl apply -f cert.yml'
                    }
                }
            }
        }

        stage("Deploy notes-app to the cluster") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh "aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l"
                        sh 'kubectl apply -f notes-app.yml'
                    }
                }
            }
        }

        stage("Setup Weave Works addon for Sock-Shop App") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh "aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l"
                        sh 'kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml'
                    }
                }
            }
        }

        stage("Deploy Sock-Shop App") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh "aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l"
                        sh 'kubectl apply -f sock-shop.yml'
                    }
                }
            }
        }

        stage("Create Ingress for applications") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l'
                        sh 'kubectl delete -f ingress.yml'
                    }
                }
            }
        }

        stage("Deploy Prometheus Manifests") {
            steps {
                script {
                    dir ('jenkins-pipeline') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l'
                        sh 'kubectl apply -f manifests-monitoring/'
                    }
                }
            }
        }

        stage("Configure DNS") {
            steps {
                script {
                    dir ('jenkins-pipeline/k8s') {
                        sh 'aws eks --region us-east-1 update-kubeconfig --name tuyojr-eks-vNp6U16l'
                        sh 'terraform init -upgrade'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}