#!/usr/bin/env groovy

pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }

        stage("Create EKS Infrastructure") {
            steps {
                script {
                    dir ('jenkins-pipeline/aws') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage("Deploy applications to the cluster") {
            steps {
                script {
                    dir (jenkins-pipeline/k8s) {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}