apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tuyojr-me-tls
  namespace: default
spec:
  dnsNames:
  - tuyojr.me
  secretName: tuyojr-me-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer