apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tuyojr-me-tls
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: olutuyod@gmail.com
    privateKeySecretRef:
      name: tuyojr-me-tls
    solvers:
    - http01:
        ingress:
          class: nginx