apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: sock-shop
# specifications to use the path based routing for the notes-app and sock-shop app on the domain tuyojr.me
# the sock-shop app is deployed in the sock-shop namespace
# the notes-app is deployed in the default namespace
spec:
  rules:
  - host: tuyojr.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  
  # add the tls section to enable TLS
  tls:
  - hosts:
    - tuyojr.me
    secretName: tuyojr.me-tls