apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
# specifications to use the path based routing for the notes-app and sock-shop app on the domain tuyojr.me
# the sock-shop app is deployed in the sock-shop namespace
# the notes-app is deployed in the default namespace
spec:
  rules:
  - host: tuyojr.me
    http:
      paths:
      - path: /notes-app
        pathType: Prefix
        backend:
          service:
            name: notes-app-service
            port:
              number: 80  
  # add the tls section to enable TLS
  tls:
  - hosts:
    - tuyojr.me
    secretName: tuyojr.me-tls
---
# Ingress for the sock-shop app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: sock-shop
spec:
  rules:
  - host: tuyojr.me
    http:
      paths:
      - path: /sock-shop
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
  tls:
  - hosts:
    - tuyojr.me
    secretName: tuyojr.me-tls